### ISSUE TITLE
Timeout on put_multi

### ISSUE THREAD

**Issue by kwando** [lucaong/cubdb#29]
Got hit by this error and there is no way to provide a larger timeout.
```
GenServer.call(TransactionWatcher.Storage, {:get_and_update_multi, [], #Function<15.65360478/1 in CubDB.put_multi/2>}, 5000)
```
11GB file with 30M entries... I know it might not be designed for this kind of data :)

**Comment by lucaong** [comment]
Hi @kwando , what version are you using? The latest rc should have a timeout option: https://hexdocs.pm/cubdb/1.0.0-rc.6/CubDB.html#get_and_update_multi/4

I should really release `v1.0.0` soon 🙂

**Comment by lucaong** [comment]
Ah wait, I see now that you meant `put_multi`. You are right, there is no timeout option for now. One possibility is to use `get_and_update_multi` instead (cumbersome, I know).

I will think about introducing a timeout, or defaulting to `:infinite`.

**Comment by lucaong** [comment]
I just set the default timeout to `:infinity` (consistently with other functions), it will be part of an upcoming `v1.0.0-rc7`.

**Comment by lucaong** [comment]
Version `1.0.0-rc.7` is released, fixing this.

**Comment by lucaong** [comment]
@kwando hopefully this should fix your issue.

That said, I am curious to know about your experience with a large CubDB database. In case you feel like sharing some opinions, you can find me on the Elixir Slack. I have used CubDB in use cases with equally large databases, usually though each individual piece of data is not too big.
