### ISSUE TITLE
CubDB 0.17.0 crash under load {:error, :enoent}

### ISSUE THREAD

**Issue by DarkMarmot** [lucaong/cubdb#32]
Hi,

Really awesome looking project! We're evaluating it as an embedded storage solution and my coworker logged this
error when testing it (I couldn't reproduce it myself). Assuming it's a timing issue with the underlying file?

Steps to potentially reproduce:

`{:ok, db} = CubDB.start_link(data_dir: "goof/", auto_compact: true) `

Works

`1..100 |> Enum.each(fn x -> CubDB.put(db, "k#{x}", "The value is #{x}") end) `

Works

`10000..20000 |> Enum.each(fn x -> CubDB.put(db, "k#{x}", "The value is #{x}") end)`

It then throws an error attempting to rename the file ` :ok = File.rename(file_path, new_path)`
when it is apparently not found (either something removed it out of order -- or the OS is acting funny). 

```
[error] GenServer #PID<0.1606.0> terminating
** (MatchError) no match of right hand side value: {:error, :enoent}
    (cubdb 0.17.0) lib/cubdb.ex:1022: CubDB.finalize_compaction/1
    (cubdb 0.17.0) lib/cubdb.ex:939: CubDB.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:catch_up, %CubDB.Btree{capacity: 32, dirt: 9903, root: {:b, [{:foo, 10999555}, {"k14136", 13286632}]}, root_loc: 13287063, size: 10102, store: %CubDB.Store.File{file_path: "goof/2.compact", pid: #PID<0.2266.0>}}, %CubDB.Btree{capacity: 32, dirt: 10003, root: {:b, [{:foo, 15659273}, {"k14088", 18968629}]}, root_loc: 18969060, size: 10102, store: %CubDB.Store.File{file_path: "goof/1.cub", pid: #PID<0.2038.0>}}}
** (EXIT from #PID<0.1160.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :enoent}
        (cubdb 0.17.0) lib/cubdb.ex:1022: CubDB.finalize_compaction/1
        (cubdb 0.17.0) lib/cubdb.ex:939: CubDB.handle_info/2
        (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Thanks!

**Comment by DarkMarmot** [comment]
I switched to using your release candidate -- didn't realize how much work you've done since the last hex release!

**Comment by lucaong** [comment]
yeah I should really release `1.0.0`, the API is stable by now ;)

**Comment by lucaong** [comment]
@DarkMarmot I will close the issue, as I expect the release candidate to fix the issue you encountered, but if you still experience the issue after updating please comment here mentioning me and I will reopen it.

**Comment by DarkMarmot** [comment]
Thanks again! Really excited to try using this is in our system! :)
