### ISSUE TITLE
transactions

### ISSUE THREAD

**Issue by lud** [lucaong/cubdb#4]
Hi, 

Is there a way to run a transaction where, istead of using `put_multi` I could issue many `put` calls ?

Thank you.

**Comment by lucaong** [comment]
Hi @lud ,
there is no `transaction do ... end` function, but arbitrary get/put/delete atomic transactions can be performed with `get_and_update_multi`.

What is your use case? Why is `put_multi` not ok? If I understand your issue better, maybe I can provide you with an example.

**Comment by lud** [comment]
Hello :)

At some point in my code I will receive multiple entities. Some have to be updated in Ecto, other will have to go in Cub ...

But yes I could accumulate the cub ones and use `put_multi` in the end. I'll try to do that in the future but I changed project at the moment, so we can close if you want.

**Comment by lucaong** [comment]
Then yes, accumulating and using `put_multi` is the best option. Unless you need to get and put values, then I would recommend `get_and_update_multi`.
