### ISSUE TITLE
Sort order for select?

### ISSUE THREAD

**Issue by Zinggi** [lucaong/cubdb#40]
Hey there :wave: 

It looks like there is no way to specify an `order_by` query in a `select` operation.

Is this a limitation of the BTree that backs up CubDB and therefore something that would be impossible to do in an efficient way?
Or would it theoretically be possible to support taking entries in an ordered way efficiently?

At the moment, what would be the best way to take the first n entries ordered by some value?

Would keeping a sorted, size limited list as an accumulator in the `reduce` of the `select` be better than just getting all entries and then `Enum.sort_by(..) |> Enum.take(n)` them at the end?

**Comment by lucaong** [comment]
Hello @Zinggi ,
The order of select is always determined by the keys: entries in the selected range are returned in ascending order of keys, or descending if you specify `reverse: true`. The order of Elixir/Erlang terms is [always specified](https://hexdocs.pm/elixir/master/operators.html#term-ordering), even for composite terms. For example, tuples are compared element by element (so `{:foo, 1} < {:foo, 2}`). Also refer to [this](https://hexdocs.pm/cubdb/howto.html) for some more explanation.

Ascending/descending key order is the only one that can be efficiently implemented at the storage level. Everything else requires a runtime sorting, which you can perform in your code, so CubDB doesn’t offer an option for it (it could not make it more performant than your own elixir code).

In sum, you can think of your keys as your database index. Designing your keys to follow the sorting order you need is the best way. If you need to select according to different sorting orders, you can either sort the entries after selecting them, your ire in some cases you could implement a secondary index by atomically writing also different key for each entry.

I hope this helps.

**Comment by Zinggi** [comment]
Hi @lucaong 

Sorry for not answering back earlier. When I asked the question I didn't realize I'd leave on holidays soon after and wouldn't be able to see your reply, very rude of me!

Thanks for you reply, this cleared up some of the questions I had regarding what can be done at the storage level. Looks like it has to be solved in user code.


> If you need to select according to different sorting orders, you can [...] re-sort the entries after selecting them [...]

This works well if you have a small collection, but in my case I have a quite large collection.
I essentially want an order by + limit + offset query.

A bit of background: I'm working on a home music server that runs on my RPi and I'm storing metadata about tracks, albums and artists in CubDB. I have a frontend where I want to browse through the collection in a paginated way, sorted e.g. by release date.
At the moment I'm doing it in the select then sort way, but it's very slow for my larger tables (tracks).
I realize that this use case would best be served by a traditional SQL DB, but I liked the simplicity of CubDB way too much to make the switch to SQLite.

So it looks like the most efficient way for my use case is to do that in the `reduce` clause. I could maintain a size limited, sorted collection in the accumulator, such that I'd never have to hold the full collection in memory.

I will try to experiment a bit with that and write back once I have a good solution, as I think the solution will be quite generic and might possibly make a good addition to the core library.

**Comment by lucaong** [comment]
Hi @Zinggi ,
if you are paginating based on your keys, the most efficient way is to use `min_key` and `max_key`, to select the range, and
`drop` and `take` options in the `pipe` to implement pagination (basically like offset and limit in a relational DB). For example, assume that you save all tracks with tuple keys like `{:track, track_id}` (where `track_id` is an integer). Then, you can paginate track, say 30 per page, like this:

```elixir
# First page:
{:ok, tracks} = CubDB.select(db,
  min_key: {:tracks, 0},
  max_key: {:tracks, nil},
  pipe: [
    take: 30
  ]
)

# Second page
{:ok, tracks} = CubDB.select(db,
  min_key: {:tracks, 0},
  max_key: {:tracks, nil},
  pipe: [
    drop: 30,
    take: 30
  ]
)
```

This works if you paginate and sort according to your "primary" key. Depending on your use-case, you might also implement some sort of secondary index. For example, if you want to also sort and paginate tracks by release date, you might create a secondary index by saving for each track also a mapping of release date to track ID. The secondary index keys could be tuples like `{:tracks_by_release_date, release_date, track_id}` (where `release_date` is an integer Unix timestamp), and the values would be the corresponding `track_id`. When inserting a track, you would use `put_multi` to atomically write the track and its secondary index. Then, you could get tracks by release date like by selecting entries in the secondary index, paginating them with `drop`/`take`, then selecting the corresponding tracks with `get_multi`:

```elixir
# First page:
{:ok, track_ids} = CubDB.select(db,
  min_key: {:tracks_by_release_date, 0, 0},
  max_key: {:tracks_by_release_date, nil, nil},
  pipe: [
    take: 30,
    map: fn {_key, value} -> value end
  ]
)

tracks = CubDB.get_multi(Enum.map(track_ids, fn id -> {:tracks, id} end))
```

Note that I did not run this code, so please expect the occasional bug, but hopefully you get the idea.

**Comment by Zinggi** [comment]
Thanks a lot for this answer, this is giving me more options.

For pagination without ordering, I already did something very similar to your suggestion for a search page:

```elixir
CubDB.select(DB,
  min_key: from_key,
  min_key_inclusive: false,
  max_key: {:track, nil},
  pipe: [
    filter: ...,
    take: 100
  ]
)
```
I might switch to your suggestion, as it is a bit simpler.

---

The suggestion with the secondary index (`{:tracks_by_release_date, release_date, track_id}`) is really good and definitely the most efficient way to do it.

I'm a bit concerned with maintaining that index though. I would have to make sure this is created on insert, updated on edit and deleted on delete. Lots of places to go wrong and end up with inconsistent data. Also, adding new sorting options means creating more indices, might be tricky to maintain that.

Anyway, I'll think about it and will experiment a bit, thanks for your help.

(I guess I'll close this issue, since it was more of a question. I'll still include an update here if I think it could be useful for someone else)
