### ISSUE TITLE
How to remove all records in a database?

### ISSUE THREAD

**Issue by undr** [lucaong/cubdb#42]
Hey there.

I'm going to use `cubdb` to store temporary logs in my app. My app has to reset the database from time to time by user request. I didn't find a way how to reset the database. Should I remove (or rename) database dir, or is there a more native way to achieve this in one operation?

**Comment by lucaong** [comment]
Hello @undr ,
if you want to clear the database completely, you can remove or rename the data directory, as you mentioned. This needs to be done while CubDB is **not** running though, so you should probably stop the CubDB process, clear the data directory, then start it again.

Your question makes me realize that I should probably add a way to clear the database without needing to stop the process (that would be quite simple, I think I can add it in the next release).
