### ISSUE TITLE
Re-opening a file fails when it was closed during compaction

### ISSUE THREAD

**Issue by dominicletz** [lucaong/cubdb#61]
Hi another edgy case when running many CubDB instances back to back:

there is `CubDB.stop()` happening just before this, but it seems as if the error message is indicating the on the next `CubDB.start_link()` the old compaction process still has a lock on the name?!

I tried adding `halt_compaction` before the stop:
```
CubDB.halt_compaction(db)
CubDB.stop(db)
```

but that didn't help either.

11:03:36.326 [error] GenServer #PID<0.266.0> terminating
** (ArgumentError) file "tmp/test_file_detsplus_bench_large_write_Elixir.CubDBWrap/1.compact" is already in use by another CubDB.Store.File
    (cubdb 2.0.0) lib/cubdb/store/file.ex:43: CubDB.Store.File.ensure_exclusive_access!/1
    (cubdb 2.0.0) lib/cubdb/store/file.ex:34: CubDB.Store.File.init/1
    (elixir 1.13.4) lib/agent/server.ex:8: Agent.Server.init/1
    (stdlib 3.15) gen_server.erl:427: :gen_server.init_it/2
    (stdlib 3.15) gen_server.erl:394: :gen_server.init_it/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.263.0>, {%ArgumentError{message: "file \"tmp/test_file_detsplus_bench_large_write_Elixir.CubDBWrap/1.compact\" is already in use by another CubDB.Store.File"}, [{CubDB.Store.File, :ensure_exclusive_access!, 1, [file: 'lib/cubdb/store/file.ex', line: 43]}, {CubDB.Store.File, :init, 1, [file: 'lib/cubdb/store/file.ex', line: 34]}, {Agent.Server, :init, 1, [file: 'lib/agent/server.ex', line: 8]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 427]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 394]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
State: %DynamicSupervisor{args: {{:temporary, 5000}, []}, children: %{}, extra_arguments: [], max_children: :infinity, max_restarts: 3, max_seconds: 5, mod: Task.Supervisor, name: {#PID<0.266.0>, Task.Supervisor}, restarts: [], strategy: :one_for_one}
```

**Comment by lucaong** [comment]
Thanks for reporting @dominicletz ! This is indeed a bug, I am looking into it.
